package net.anware.tmc.colourscroller.scrollables;

import net.minecraft.block.Blocks;

import static net.anware.tmc.colourscroller.ScrollableHelper.addSet;


public class ColourScrollables {
    public static void init() {
        addSet("colour", Blocks.WHITE_WOOL, Blocks.LIGHT_GRAY_WOOL, Blocks.GRAY_WOOL, Blocks.BLACK_WOOL,
                Blocks.RED_WOOL, Blocks.BROWN_WOOL, Blocks.ORANGE_WOOL, Blocks.YELLOW_WOOL,
                Blocks.LIME_WOOL, Blocks.GREEN_WOOL, Blocks.CYAN_WOOL, Blocks.LIGHT_BLUE_WOOL,
                Blocks.BLUE_WOOL, Blocks.PINK_WOOL, Blocks.MAGENTA_WOOL, Blocks.PURPLE_WOOL);

        addSet("colour", Blocks.WHITE_CONCRETE, Blocks.LIGHT_GRAY_CONCRETE, Blocks.GRAY_CONCRETE, Blocks.BLACK_CONCRETE,
                Blocks.RED_CONCRETE, Blocks.BROWN_CONCRETE, Blocks.ORANGE_CONCRETE, Blocks.YELLOW_CONCRETE,
                Blocks.LIME_CONCRETE, Blocks.GREEN_CONCRETE, Blocks.CYAN_CONCRETE, Blocks.LIGHT_BLUE_CONCRETE,
                Blocks.BLUE_CONCRETE, Blocks.PINK_CONCRETE, Blocks.MAGENTA_CONCRETE, Blocks.PURPLE_CONCRETE);

        addSet("colour", Blocks.WHITE_CONCRETE_POWDER, Blocks.LIGHT_GRAY_CONCRETE_POWDER, Blocks.GRAY_CONCRETE_POWDER, Blocks.BLACK_CONCRETE_POWDER,
                Blocks.RED_CONCRETE_POWDER, Blocks.BROWN_CONCRETE_POWDER, Blocks.ORANGE_CONCRETE_POWDER, Blocks.YELLOW_CONCRETE_POWDER,
                Blocks.LIME_CONCRETE_POWDER, Blocks.GREEN_CONCRETE_POWDER, Blocks.CYAN_CONCRETE_POWDER, Blocks.LIGHT_BLUE_CONCRETE_POWDER,
                Blocks.BLUE_CONCRETE_POWDER, Blocks.PINK_CONCRETE_POWDER, Blocks.MAGENTA_CONCRETE_POWDER, Blocks.PURPLE_CONCRETE_POWDER);

        addSet("colour", Blocks.WHITE_TERRACOTTA, Blocks.LIGHT_GRAY_TERRACOTTA, Blocks.GRAY_TERRACOTTA, Blocks.BLACK_TERRACOTTA,
                Blocks.RED_TERRACOTTA, Blocks.BROWN_TERRACOTTA, Blocks.ORANGE_TERRACOTTA, Blocks.YELLOW_TERRACOTTA,
                Blocks.LIME_TERRACOTTA, Blocks.GREEN_TERRACOTTA, Blocks.CYAN_TERRACOTTA, Blocks.LIGHT_BLUE_TERRACOTTA,
                Blocks.BLUE_TERRACOTTA, Blocks.PINK_TERRACOTTA, Blocks.MAGENTA_TERRACOTTA, Blocks.PURPLE_TERRACOTTA);

        addSet("colour", Blocks.WHITE_GLAZED_TERRACOTTA, Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA, Blocks.GRAY_GLAZED_TERRACOTTA, Blocks.BLACK_GLAZED_TERRACOTTA,
                Blocks.RED_GLAZED_TERRACOTTA, Blocks.BROWN_GLAZED_TERRACOTTA, Blocks.ORANGE_GLAZED_TERRACOTTA, Blocks.YELLOW_GLAZED_TERRACOTTA,
                Blocks.LIME_GLAZED_TERRACOTTA, Blocks.GREEN_GLAZED_TERRACOTTA, Blocks.CYAN_GLAZED_TERRACOTTA, Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA,
                Blocks.BLUE_GLAZED_TERRACOTTA, Blocks.PINK_GLAZED_TERRACOTTA, Blocks.MAGENTA_GLAZED_TERRACOTTA, Blocks.PURPLE_GLAZED_TERRACOTTA);

        addSet("colour", Blocks.WHITE_STAINED_GLASS, Blocks.LIGHT_GRAY_STAINED_GLASS, Blocks.GRAY_STAINED_GLASS, Blocks.BLACK_STAINED_GLASS,
                Blocks.RED_STAINED_GLASS, Blocks.BROWN_STAINED_GLASS, Blocks.ORANGE_STAINED_GLASS, Blocks.YELLOW_STAINED_GLASS,
                Blocks.LIME_STAINED_GLASS, Blocks.GREEN_STAINED_GLASS, Blocks.CYAN_STAINED_GLASS, Blocks.LIGHT_BLUE_STAINED_GLASS,
                Blocks.BLUE_STAINED_GLASS, Blocks.PINK_STAINED_GLASS, Blocks.MAGENTA_STAINED_GLASS, Blocks.PURPLE_STAINED_GLASS);

        addSet("colour", Blocks.WHITE_STAINED_GLASS_PANE, Blocks.LIGHT_GRAY_STAINED_GLASS_PANE, Blocks.GRAY_STAINED_GLASS_PANE, Blocks.BLACK_STAINED_GLASS_PANE,
                Blocks.RED_STAINED_GLASS_PANE, Blocks.BROWN_STAINED_GLASS_PANE, Blocks.ORANGE_STAINED_GLASS_PANE, Blocks.YELLOW_STAINED_GLASS_PANE,
                Blocks.LIME_STAINED_GLASS_PANE, Blocks.GREEN_STAINED_GLASS_PANE, Blocks.CYAN_STAINED_GLASS_PANE, Blocks.LIGHT_BLUE_STAINED_GLASS_PANE,
                Blocks.BLUE_STAINED_GLASS_PANE, Blocks.PINK_STAINED_GLASS_PANE, Blocks.MAGENTA_STAINED_GLASS_PANE, Blocks.PURPLE_STAINED_GLASS_PANE);

        addSet("colour", Blocks.WHITE_SHULKER_BOX, Blocks.LIGHT_GRAY_SHULKER_BOX, Blocks.GRAY_SHULKER_BOX, Blocks.BLACK_SHULKER_BOX,
                Blocks.RED_SHULKER_BOX, Blocks.BROWN_SHULKER_BOX, Blocks.ORANGE_SHULKER_BOX, Blocks.YELLOW_SHULKER_BOX,
                Blocks.LIME_SHULKER_BOX, Blocks.GREEN_SHULKER_BOX, Blocks.CYAN_SHULKER_BOX, Blocks.LIGHT_BLUE_SHULKER_BOX,
                Blocks.BLUE_SHULKER_BOX, Blocks.PINK_SHULKER_BOX, Blocks.MAGENTA_SHULKER_BOX, Blocks.PURPLE_SHULKER_BOX);

        addSet("colour", Blocks.WHITE_CARPET, Blocks.LIGHT_GRAY_CARPET, Blocks.GRAY_CARPET, Blocks.BLACK_CARPET,
                Blocks.RED_CARPET, Blocks.BROWN_CARPET, Blocks.ORANGE_CARPET, Blocks.YELLOW_CARPET,
                Blocks.LIME_CARPET, Blocks.GREEN_CARPET, Blocks.CYAN_CARPET, Blocks.LIGHT_BLUE_CARPET,
                Blocks.BLUE_CARPET, Blocks.PINK_CARPET, Blocks.MAGENTA_CARPET, Blocks.PURPLE_CARPET);

    }
}